Repository openai/openai-agents-js, pull requests merged in 2025-07, with the labels that each got.

#167 fix: correct typo in RealtimeTransportEventTypes identifier
  .changeset/funny-memes-cover.md
  docs/src/content/docs/guides/voice-agents/transport.mdx
  docs/src/content/docs/ja/guides/voice-agents/transport.mdx
  packages/agents-realtime/src/index.ts
  packages/agents-realtime/src/openaiRealtimeBase.ts
  packages/agents-realtime/src/transportLayer.ts
  packages/agents-realtime/src/transportLayerEvents.ts
  packages/agents-realtime/test/stubs.ts
Labels: bug, documentation, package:agents-realtime

#156 Fix #131 Human in the Loop MCP approval fails
  packages/agents-core/src/runState.ts
  packages/agents-core/test/runState.test.ts
Labels: bug, package:agents-core

#197 Update Japanese docs to reflect the latest changes
  docs/src/content/docs/guides/release.mdx
  docs/src/content/docs/ja/extensions/ai-sdk.mdx
  docs/src/content/docs/ja/extensions/twilio.mdx
  docs/src/content/docs/ja/guides/agents.mdx
  docs/src/content/docs/ja/guides/config.mdx
  docs/src/content/docs/ja/guides/context.mdx
  docs/src/content/docs/ja/guides/guardrails.mdx
  docs/src/content/docs/ja/guides/handoffs.mdx
  docs/src/content/docs/ja/guides/human-in-the-loop.mdx
  docs/src/content/docs/ja/guides/mcp.mdx
  docs/src/content/docs/ja/guides/models.mdx
  docs/src/content/docs/ja/guides/multi-agent.md
  docs/src/content/docs/ja/guides/quickstart.mdx
  docs/src/content/docs/ja/guides/release.mdx
  docs/src/content/docs/ja/guides/results.mdx
  docs/src/content/docs/ja/guides/running-agents.mdx
  docs/src/content/docs/ja/guides/streaming.mdx
  docs/src/content/docs/ja/guides/tools.mdx
  docs/src/content/docs/ja/guides/tracing.mdx
  docs/src/content/docs/ja/guides/troubleshooting.mdx
  docs/src/content/docs/ja/guides/voice-agents.mdx
  docs/src/content/docs/ja/guides/voice-agents/build.mdx
  docs/src/content/docs/ja/guides/voice-agents/quickstart.mdx
  docs/src/content/docs/ja/guides/voice-agents/transport.mdx
  docs/src/content/docs/ja/index.mdx
  docs/src/scripts/translate.ts
Labels: documentation

#196 Tentative fix for #187 : Lock zod version to <=3.25.67 (prev: >=3.25.40 <4)
  .changeset/odd-rice-call.md
  .github/workflows/test.yml
  docs/package-lock.json
  examples/agent-patterns/package.json
  examples/ai-sdk/package.json
  examples/basic/package.json
  examples/customer-service/package.json
  examples/docs/package.json
  examples/financial-research-agent/package.json
  examples/handoffs/package.json
  examples/mcp/package.json
  examples/model-providers/package.json
  examples/nextjs/package.json
  examples/realtime-next/package.json
  examples/realtime-twilio/package.json
  examples/research-bot/package.json
  examples/tools/package.json
  package.json
  packages/agents-core/package.json
  packages/agents-core/src/metadata.ts
  packages/agents-extensions/package.json
  packages/agents-extensions/src/metadata.ts
  packages/agents-openai/package.json
  packages/agents-openai/src/metadata.ts
  packages/agents-realtime/package.json
  packages/agents-realtime/src/metadata.ts
  pnpm-lock.yaml
Labels: bug, package:agents-core, dependencies

#199 Run pnpm update for upgrading dev dependencies
  package.json
  pnpm-lock.yaml
Labels: project

#184 Fix #175 by removing system.exit calls in the built-in handlers
  .changeset/tame-hotels-hope.md
  .github/workflows/test.yml
  packages/agents-core/src/tracing/provider.ts
Labels: bug, package:agents-core

#200 Update documents with workaround for #187
  README.md
  docs/src/content/docs/guides/quickstart.mdx
  docs/src/content/docs/guides/voice-agents/quickstart.mdx
  docs/src/content/docs/index.mdx
  docs/src/content/docs/ja/guides/quickstart.mdx
  docs/src/content/docs/ja/guides/voice-agents/quickstart.mdx
  docs/src/content/docs/ja/index.mdx
  packages/agents/README.md
Labels: documentation, dependencies

#205 fix(core): emit correct agent in agent_updated_stream_event during streaming handoff
  .changeset/twelve-poets-mate.md
  packages/agents-core/src/run.ts
  packages/agents-core/test/run.stream.test.ts
Labels: bug, package:agents-core

#163 feat: support speed session configuration
  .changeset/silly-geese-wear.md
  packages/agents-realtime/src/clientMessages.ts
  packages/agents-realtime/src/openaiRealtimeBase.ts
Labels: enhancement, package:agents-realtime

#209 feat: support noise reduction argument for session
  .changeset/metal-cases-beg.md
  docs/src/content/docs/guides/voice-agents/quickstart.mdx
  docs/src/content/docs/ja/guides/voice-agents/quickstart.mdx
  packages/agents-realtime/src/clientMessages.ts
  packages/agents-realtime/src/openaiRealtimeBase.ts
Labels: enhancement, package:agents-realtime

#220 fix(realtime-ws): stop accidental cancellation error
  .changeset/strong-lobsters-repair.md
  packages/agents-extensions/src/TwilioRealtimeTransport.ts
  packages/agents-extensions/test/TwilioRealtimeTransport.test.ts
  packages/agents-extensions/test/index.test.ts
  packages/agents-realtime/src/openaiRealtimeBase.ts
  packages/agents-realtime/src/openaiRealtimeWebsocket.ts
Labels: bug, package:agents-realtime

#218 Fix typos across repo
  .changeset/tame-deers-shake.md
  docs/src/content/docs/extensions/twilio.mdx
  docs/src/content/docs/guides/mcp.mdx
  docs/src/content/docs/guides/results.mdx
  docs/src/content/docs/guides/voice-agents/quickstart.mdx
  examples/docs/results/historyLoop.ts
  examples/handoffs/index.ts
  examples/tools/web-search.ts
  packages/agents-core/src/agent.ts
  packages/agents-core/src/extensions/handoffFilters.ts
  packages/agents-core/src/handoff.ts
  packages/agents-core/src/run.ts
  packages/agents-core/src/runImplementation.ts
  packages/agents-core/src/tool.ts
  packages/agents-core/src/tracing/processor.ts
  packages/agents-core/src/types/protocol.ts
  packages/agents-openai/CHANGELOG.md
  packages/agents-realtime/src/clientMessages.ts
  packages/agents-realtime/src/openaiRealtimeBase.ts
Labels: documentation, codex

#226 Workaround for pnpm install error with node 24.4
  .github/workflows/test.yml
Labels: project

#230 docs(index): fix missing comma
  docs/src/content/docs/index.mdx
Labels: documentation

#231 Fix release tagging
  .github/workflows/release.yml
Labels: codex, project

#232 Revert "Fix release tagging"
  .github/workflows/release.yml
Labels: project

#238 feat(realtime): make websocket URL configurable
  .changeset/realtime-url-configurable.md
  packages/agents-realtime/src/openaiRealtimeWebsocket.ts
  packages/agents-realtime/src/realtimeSession.ts
  packages/agents-realtime/test/openaiRealtimeWebsocket.test.ts
  packages/agents-realtime/test/realtimeSession.test.ts
Labels: enhancement, codex, package:agents-realtime

#241 Fix #20 Update metadata.ts files when releasing a new version
  .github/workflows/release.yml
Labels: project

#240 Fix #219 MCPServer#invalidateToolsCache() not exposed while being mentioned in the documents
  .changeset/open-candies-watch.md
  packages/agents-core/src/mcp.ts
  packages/agents-core/src/shims/mcp-server/browser.ts
  packages/agents-core/src/shims/mcp-server/node.ts
  packages/agents-core/test/mcpCache.test.ts
Labels: enhancement, package:agents-core

#236 fix: emit audio_start event when audio begins
  .changeset/wise-cats-tell.md
  packages/agents-realtime/src/realtimeSession.ts
  packages/agents-realtime/test/realtimeSession.test.ts
Labels: bug, package:agents-realtime

#250 Fix #246 by exposing RunHandoffOutputItem type
  .changeset/tender-turtles-carry.md
  packages/agents-core/src/index.ts
Labels: bug, package:agents-core

#254 ci(docs): automate docs translation
  .github/workflows/update-docs.yml
Labels: documentation, codex, project

#256 Improve the release operation jobs
  .github/workflows/release-tag.yml
  .github/workflows/release.yml
  package.json
Labels: project

#260 fix: persist container_id in codeInterpreterTool history
  .changeset/stale-times-bathe.md
  packages/agents-openai/src/openaiResponsesModel.ts
Labels: package:agents-openai

#262 Remove gpt-4.5 usage in examples
  examples/financial-research-agent/agents.ts
Labels: documentation

#164 Add MCP server tool filtering support to agents-js
  .changeset/hungry-suns-search.md
  docs/src/content/docs/guides/mcp.mdx
  examples/docs/mcp/tool-filter.ts
  examples/mcp/README.md
  examples/mcp/package.json
  examples/mcp/tool-filter-example.ts
  package.json
  packages/agents-core/src/agent.ts
  packages/agents-core/src/index.ts
  packages/agents-core/src/mcp.ts
  packages/agents-core/src/mcpUtil.ts
  packages/agents-core/src/run.ts
  packages/agents-core/src/runState.ts
  packages/agents-core/src/shims/mcp-server/node.ts
  packages/agents-core/test/mcpCache.test.ts
  packages/agents-core/test/mcpToolFilter.integration.test.ts
  packages/agents-core/test/mcpToolFilter.test.ts
  packages/agents-realtime/src/realtimeSession.ts
Labels: enhancement, package:agents-core, package:agents-realtime

#265 Use Node 22 for updating documents
  .github/workflows/update-docs.yml
Labels: documentation

#263 Fix #259 Failing to send trace data with usage for ai-sdk models
  .changeset/evil-things-guess.md
  packages/agents-extensions/src/aiSdk.ts
Labels: bug

#267 Enable test job to run when receiving PRs created by a Github Actions job
  .github/workflows/test.yml
Labels: project

#268 Add push event trigger to test.yml
  .github/workflows/test.yml
Labels: project
